### ISSUE TITLE
[BUG] ArgumentOutOfRangeException when assigning system sounds to a slider

### ISSUE THREAD

**Issue by aroldmi** [ho0ber/NK2Tray#73]
If i want to assign the system sounds to any slider I get the following exception (I translated the text to english):

************** Exception text **************
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parametername: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NK2Tray.Fader.convertToApplicationPath(String ident)
   at NK2Tray.Fader.Assign(MixerSession mixerSession)
   at NK2Tray.SysTrayApp.AssignFader(Object sender, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Command.DispatchID(Int32 id)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

It doesnt matter which slider I want to use.
I am using Windows 10 1909 and the Korg nanoKontrol2.

<details> 
  <summary>Full expetion message in german</summary>

> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.ArgumentOutOfRangeException: StartIndex darf nicht kleiner als Null sein.
> Parametername: startIndex
>    bei System.String.Substring(Int32 startIndex, Int32 length)
>    bei NK2Tray.Fader.convertToApplicationPath(String ident)
>    bei NK2Tray.Fader.Assign(MixerSession mixerSession)
>    bei NK2Tray.SysTrayApp.AssignFader(Object sender, EventArgs e)
>    bei System.Windows.Forms.MenuItem.OnClick(EventArgs e)
>    bei System.Windows.Forms.MenuItem.MenuItemData.Execute()
>    bei System.Windows.Forms.Command.Invoke()
>    bei System.Windows.Forms.Command.DispatchID(Int32 id)
>    bei System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
>    bei System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> NK2Tray
>     Assembly-Version: 0.0.16.0.
>     Win32-Version: 0.0.16.0.
>     CodeBase: file:///C:/Users/Michael/Desktop/Programme/NK2Tray/NK2Tray.exe.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4150.0 built by: NET48REL1LAST_C.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4110.0 built by: NET48REL1LAST_B.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3761.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3761.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.4180.0 built by: NET48REL1LAST_B.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3761.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> NAudio
>     Assembly-Version: 1.8.5.0.
>     Win32-Version: 0.0.16.0.
>     CodeBase: file:///C:/Users/Michael/Desktop/Programme/NK2Tray/NK2Tray.exe.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3761.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.8.3761.0 built by: NET48REL1.
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
> Ausnahmen an den JIT-Debugger gesendet, der auf dem
> Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

</details>

**Comment by aroldmi** [comment]
This issue already exist. I looked but i didn't see it.
-> #70
